# Generated by Django 2.0.13 on 2022-11-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcode', models.IntegerField()),
                ('fName', models.CharField(max_length=50)),
                ('fModel', models.CharField(max_length=50)),
                ('fDesc', models.CharField(max_length=250)),
            ],
        ),
    ]
