# Generated by Django 2.0.13 on 2022-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221122_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Music_Name', models.CharField(max_length=50)),
                ('Music_singer', models.CharField(max_length=50)),
                ('Music_Maker', models.CharField(max_length=50)),
                ('Music_Link', models.CharField(max_length=50)),
            ],
        ),
    ]
